#!/usr/bin/env bash
# 1. Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.html
sudo service nginx restart
