#!/usr/bin/env bash
# 1. Install nginx web server

sudo apt-get -y update
sudo apt-get install -y nginx
sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
