#!/usr/bin/env bash
# 3. Redirection

sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start

echo 'Holberton School' > /var/www/html/index.nginx-debian.html

new_string="\\\tlocation /redirect_me {\n\t\t return 301 https://www.google.com;\n\t}\n"
sed -i "30i $new_string" /etc/nginx/sites-available/default

sudo service nginx restart
