#!/usr/bin/env bash
# 3. Redirection

sudo apt-get -y update
sudo apt-get install -y nginx
sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html
printf %s "server {
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" >> /etc/nginx/sites-available/default
sudo service nginx restart
