#!/usr/bin/env bash
# 3. Redirection
printf %s "server {
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" >> /etc/nginx/sites-available/default
service nginx restart
