#!/usr/bin/env bash
# 4. Not found page 404

sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start

echo 'Holberton School' > /var/www/html/index.nginx-debian.html

new_string="\\\tlocation /redirect_me {\n\t\t return 301 https://www.google.com;\n\t}\n"
sed -i "30i $new_string" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > sudo tee /var/www/html/404.html

new_string="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sed -i "33a $new_string" /etc/nginx/sites-available/default

sudo service nginx restart
