#!/usr/bin/env bash
# Configures a brand new Ubuntu machine
# Configure Nginx so that its HTTP response contains a custom header
# - The name of the custom HTTP header must be X-Served-By
# - The value of the custom HTTP header must be the hostname
#   of the server Nginx is running on

sudo apt-get -y update
sudo apt-get install -y nginx

echo 'Holberton School' > /var/www/html/index.nginx-debian.html

# configure rediction when visit path /redirect_me
new_string="\\\tlocation /redirect_me {\n\t\t return 301 https://www.google.com;\n\t}\n"
sed -i "30i $new_string" /etc/nginx/sites-available/default

# configure custom 404 page
echo "Ceci n'est pas une page" > sudo tee /var/www/html/404.html

new_string="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n\t}"
sed -i "34i $new_string" /etc/nginx/sites-enabled/default

# configure custom HTTP Header. X-Served-By: name of Ubuntu machine
new_string="\\\\n\tadd_header X-Served-By $HOSTNAME;\n"
sed -i "19i $new_string" /etc/nginx/sites-enabled/default

sudo service nginx restart
