#!/usr/bin/env bash
# Bash script that:
# - Creates the file /var/run/holbertonscript.pid containing its PID
# - Displays 'To infinity and beyond' indefinitely
# - Displays 'I hate the kill command' when receiving a SIGTERM signal
# Displays 'Y U no love me?!' when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and
# terminates itself when receiving a SIGQUIT or SIGTERM signal

trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'sudo rm /var/run/holbertonscript.pid' SIGQUIT, SIGTERM
trap 'echo "I hate the kill command"; exit' SIGTERM

sudo touch /var/run/holbertonscript.pid
echo $$ > sudo /var/run/holbertonscript.pid

on=1
while [ "$on" ]
do
	echo "To infinity and beyond"
	sleep 2
done
