#!/usr/bin/env bash
# Run Nginx as Nginx
pkill apache2
sudo service nginx stop
chown nginx:nginx /etc/nginx/nginx.conf
chmod ug+rw /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
